INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_BEAMFORMER beamformer)

FIND_PATH(
    BEAMFORMER_INCLUDE_DIRS
    NAMES beamformer/api.h
    HINTS $ENV{BEAMFORMER_DIR}/include
        ${PC_BEAMFORMER_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    BEAMFORMER_LIBRARIES
    NAMES gnuradio-beamformer
    HINTS $ENV{BEAMFORMER_DIR}/lib
        ${PC_BEAMFORMER_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(BEAMFORMER DEFAULT_MSG BEAMFORMER_LIBRARIES BEAMFORMER_INCLUDE_DIRS)
MARK_AS_ADVANCED(BEAMFORMER_LIBRARIES BEAMFORMER_INCLUDE_DIRS)

